service: aws-serverless-boilerpate

plugins:
      - serverless-webpack
      - serverless-offline

custom:
      stage: ${opt:stage, self:provider.stage}
      tableThroughputs:
            prod: 5
            default: 1
      tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
      webpack:
            webpackConfig: ./webpack.config.js
            includeModules: true

provider:
      name: aws
      runtime: nodejs8.10
      stage: dev
      region: us-east-1
      environment:
            tableName:
                  Ref: ItemsTable
      iamRoleStatements:
            - Effect: Allow
              Action:
                  - dynamodb:DescribeTable
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
              Resource:
                  - "Fn::GetAtt": [ ItemsTable, Arn ]

functions:
      get:
            handler: lambda/get.main
            events:
                  - http:
                        cors: true
                        path: notes/{id}
                        method: get
                        authorizer: aws_iam
      list:
            handler: - ${file(resources/dynamodb-table.yml)}lambda/list.main
            events:
                  - http:
                        cors: true
                        path: notes
                        method: get
                        authorizer: aws_iam
      update:
            handler: lambda/update.main
            events:
                  - http:
                        cors: true
                        path: notes/{id}
                        method: put
                        authorizer: aws_iam
      delete:
            handler: lambda/delete.main
            events:
                  - http:
                        cors: true
                        path: notes/{id}
                        method: delete
                        authorizer: aws_iam
      create:
            handler: lambda/create.main
            events:
                  - http:
                        cors: true
                        path: notes
                        method: post
                        authorizer: aws_iam

resources:
      # DynamoDB
      - ${file(resources/dynamodb-table.yml)}