service: notes-app-api

plugins:
      - serverless-webpack
      - serverless-offline

custom:
      webpack:
            webpackConfig: ./webpack.config.js
            includeModules: true

provider:
      name: aws
      runtime: nodejs8.10
      stage: prod
      region: us-east-1
      iamRoleStatements:
            - Effect: Allow
              Action:
                  - dynamodb:DescribeTable
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
              Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
      get:
            handler: get.main
            events:
                  - http:
                        cors: true
                        path: notes/{id}
                        method: get
                        authorizer: aws_iam
      list:
            handler: list.main
            events:
                  - http:
                        cors: true
                        path: notes
                        method: get
                        authorizer: aws_iam
      update:
            handler: update.main
            events:
                  - http:
                        cors: true
                        path: notes/{id}
                        method: put
                        authorizer: aws_iam
      delete:
            handler: delete.main
            events:
                  - http:
                        cors: true
                        path: notes/{id}
                        method: delete
                        authorizer: aws_iam
      create:
            handler: lambda/create.main
            events:
                  - http:
                        cors: true
                        path: notes
                        method: post
                        authorizer: aws_iam