Resources:
      ItemsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                  TableName: ${self:custom.stage}-items
                  AttributeDefinitions:
                        - AttributeName: userId
                          AttributeType: S
                        - AttributeName: itemId
                          AttributeType: S
                  KeySchema:
                        - AttributeName: userId
                          KeyType: HASH
                        - AttributeName: itemId
                          KeyType: RANGE
                  ProvisionedThroughput:
                        ReadCapacityUnits: ${self:custom.tableThroughput}
                        WriteCapacityUnits: ${self:custom.tableThroughput}